export default [
    {
        name:"noland",
        img:"shop_placeholder.png"
    },
    {
        name:"john",
        img:"shop_placeholder.png"
    },
    {
        name:"crame",
        img:"shop_placeholder.png"
    },
    {
        name:"Jort",
        img:"shop_placeholder.png"
    },
    {
        name:"Paul",
        img:"shop_placeholder.png"
    },
    {
        name:"Ghoul",
        img:"shop_placeholder.png"
    },
    {
        name:"Bowl",
        img:"shop_placeholder.png"
    },
    {
        name:"Rowwen",
        img:"shop_placeholder.png"
    },
    {
        name:"Jen",
        img:"shop_placeholder.png"
    },
    {
        name:"Owen",
        img:"shop_placeholder.png"
    },
    {
        name:"Jenny",
        img:"shop_placeholder.png"
    },
    {
        name:"Dianne",
        img:"shop_placeholder.png"
    },
    {
        name:"Tan",
        img:"shop_placeholder.png"
    }

]