export default [
    {
        id: 1,
        name: "Jumbler Toy1",
        img: "bg_1.jpg",
        price: 300.00,
        rating: 4,
        quantity: 180,
    },
    {
        id: 2,
        name: "Jumbler Toy2",
        img: "bg_1.jpg",
        price: 300.00,
        rating: 2,
        quantity: 90,
    },
    {
        id: 3,
        name: "Jumbler Toy3",
        img: "bg_1.jpg",
        price: 300.00,
        rating: 3,
        quantity: 92,
    },
    {
        id: 4,
        name: "Jumbler Toy4",
        img: "bg_1.jpg",
        price: 300.00,
        rating: 5,
        quantity: 10,
    },
    {
        id: 5,
        name: "Jumbler Toy5",
        img: "bg_1.jpg",
        price: 300.00,
        rating: 1,
        quantity: 89,
    },
    {
        id: 6,
        name: "Jumbler Toy6",
        img: "bg_1.jpg",
        price: 300.00,
        rating: 1,
        quantity: 89,

    },
    {
        id: 7,
        name: "Jumbler Toy7",
        img: "bg_1.jpg",
        price: 300.00,
        rating: 1,
        quantity: 89,
    },
    {
        id: 8,
        name: "Jumbler Toy8",
        img: "bg_1.jpg",
        price: 300.00,
        rating: 1,
        quantity: 89,
    },
    {
        id: 9,
        name: "Jumbler Toy9",
        img: "shop_placeholder.png",
        price: 300.00,
        rating: 1,
        quantity: 89,
    },
    {
        id: 10,
        name: "Jumbler Toy10",
        img: "shop_placeholder.png",
        price: 300.00,
        rating: 1,
        quantity: 89,
    },
    {
        id: 11,
        name: "Jumbler Toy11",
        img: "shop_placeholder.png",
        price: 300.00,
        rating: 1,
        quantity: 89,
    },
    {
        id: 12,
        name: "Jumbler Toy12",
        img: "shop_placeholder.png",
        price: 300.00,
        rating: 1,
        quantity: 89,
    },
    {
        id: 13,
        name: "Jumbler Toy13",
        img: "shop_placeholder.png",
        price: 300.00,
        rating: 1,
        quantity: 89,
    },
    {
        id: 14,
        name: "Jumbler Toy14",
        img: "shop_placeholder.png",
        price: 300.00,
        rating: 1,
        quantity: 89,
    },
]